export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const SAVE_CONTACT_DETAILS_REQUEST = 'SAVE_CONTACT_DETAILS_REQUEST';
export const SAVE_CONTACT_DETAILS_SUCCESS = 'SAVE_CONTACT_DETAILS_SUCCESS';
export const SAVE_CONTACT_DETAILS_ERROR = 'SAVE_CONTACT_DETAILS_ERROR';
export const SAVE_CONTACT_DETAILS_RESET = 'SAVE_CONTACT_DETAILS_RESET';

export const SAVE_PROFILE_REQUEST = "SAVE_PROFILE_REQUEST"
export const SAVE_PROFILE_SUCCESS = "SAVE_PROFILE_SUCCESS"
export const SAVE_PROFILE_ERROR = "SAVE_PROFILE_ERROR"

export const CREATE_NOTIFICATION_REQUEST = "CREATE_NOTIFICATION_REQUEST"
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS"
export const CREATE_NOTIFICATION_ERROR = "CREATE_NOTIFICATION_ERROR"
export const RESET_NOTIFICATION_SUCCESS = "RESET_NOTIFICATION_SUCCESS"

export const FETCH_NOTIFICATION_REQUEST = "FETCH_NOTIFICATION_REQUEST"
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS"
export const FETCH_NOTIFICATION_ERROR = "FETCH_NOTIFICATION_ERROR"

export const NOTIFICATION_SEEN_REQUEST = "NOTIFICATION_SEEN_REQUEST"
export const NOTIFICATION_SEEN_SUCCESS = "NOTIFICATION_SEEN_SUCCESS"
export const NOTIFICATION_SEEN_ERROR = "NOTIFICATION_SEEN_ERROR"

export const EDIT_NOTIFICATION_REQUEST = "EDIT_NOTIFICATION_REQUEST"
export const EDIT_NOTIFICATION_SUCCESS = "EDIT_NOTIFICATION_SUCCESS"
export const EDIT_NOTIFICATION_ERROR = "EDIT_NOTIFICATION_ERROR"

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST"
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS"
export const DELETE_NOTIFICATION_ERROR = "DELETE_NOTIFICATION_ERROR"

export const DELETE_ACCOUNT_REQUEST = "DELETE_ACCOUNT_REQUEST"
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS"
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR"
export const RESET_DELETE_ACCOUNT = "RESET_DELETE_ACCOUNT"

export const REACTIVATE_ACCOUNT_REQUEST = "REACTIVATE_ACCOUNT_REQUEST"
export const REACTIVATE_ACCOUNT_SUCCESS = "REACTIVATE_ACCOUNT_SUCCESS"
export const REACTIVATE_ACCOUNT_ERROR = "REACTIVATE_ACCOUNT_ERROR"
// export const RESET_DELETE_ACCOUNT = "RESET_DELETE_ACCOUNT"

export const GET_USER_CARTDETAILS_REQUEST="GET_USER_CARTDETAILS_REQUEST"
export const GET_USER_CARTDETAILS_SUCCESS="GET_USER_CARTDETAILS_SUCCESS"
export const GET_USER_CARTDETAILS_ERROR="GET_USER_CARTDETAILS_ERROR"

export const CLEAR_ERRORS = "CLEAR_ERRORS";
